# Generated by Django 2.1.7 on 2019-08-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=255)),
                ('length', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('is_enable', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championship', models.CharField(choices=[('f2', 'f2'), ('f3', 'f3'), ('fe', 'fe')], default='f2', max_length=2)),
                ('team_id', models.IntegerField()),
                ('team_name', models.CharField(max_length=255)),
                ('team_logo', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Team'),
        ),
    ]
