# Generated by Django 2.1.7 on 2019-08-16 13:53

from django.db import migrations, models

def initDataToTables(apps, schema_editor):
    Team = apps.get_model("user", "Team")
    team = Team(championship='f2', team_id=1, team_name='Carlin', team_logo='team-logoCarlin.png')
    team.save()
    team = Team(championship='f2', team_id=2, team_name='ART Grand Prix', team_logo='team-logoART_GP.png')
    team.save()
    team = Team(championship='f2', team_id=3, team_name='DAMS', team_logo='team-logoDams2.png')
    team.save()
    team = Team(championship='f2', team_id=4, team_name='UNI-Virtuosi Racing', team_logo='team-logoUNI-Virtuosi2018.png')
    team.save()
    team = Team(championship='f2', team_id=5, team_name='PREMA Racing', team_logo='team-logoPrema.png')
    team.save()
    team = Team(championship='f2', team_id=6, team_name='Sauber Junior Team by Charouz', team_logo='team-logoSauberJuniorTeam.png')
    team.save()
    team = Team(championship='f2', team_id=7, team_name='Campos Racing', team_logo='team-logoCamposRacing.png')
    team.save()
    team = Team(championship='f2', team_id=8, team_name='MP Motorsport', team_logo='team-logoMPMotorsport2018_2.png')
    team.save()
    team = Team(championship='f2', team_id=9, team_name='BWT Arden', team_logo='team-logoBWT-Arden2018.png')
    team.save()
    team = Team(championship='f2', team_id=10, team_name='Trident', team_logo='team-logoTrident2018_2.png')
    team.save()
    team = Team(championship='f3', team_id=1, team_name='ART Grand Prix', team_logo='ART_logoHome.jpg')
    team.save()
    team = Team(championship='f3', team_id=2, team_name='MP Motorsport', team_logo='MP_logoHome.jpg')
    team.save()
    team = Team(championship='f3', team_id=3, team_name='Sauber Junior Team by Charouz', team_logo='Sauber_logoHome.jpg')
    team.save()
    team = Team(championship='f3', team_id=4, team_name='HWA RACELAB', team_logo='HWA_logoHome.jpg')
    team.save()
    team = Team(championship='f3', team_id=5, team_name='Jenzer Motorsport', team_logo='Jenzer_logoHome.jpg')
    team.save()
    team = Team(championship='f3', team_id=6, team_name='Trident', team_logo='Trident_logoHome.jpg')
    team.save()
    team = Team(championship='f3', team_id=7, team_name='Hitech Grand Prix', team_logo='Hitech_logoHome.jpg')
    team.save()
    team = Team(championship='f3', team_id=8, team_name='Campos Racing', team_logo='Campos_logoHome.jpg')
    team.save()
    team = Team(championship='f3', team_id=9, team_name='Prema Racing', team_logo='PREMA_logoHome.jpg')
    team.save()
    team = Team(championship='f3', team_id=10, team_name='Carlin Buzz Racing', team_logo='Carlin_logoHome.jpg')
    team.save()

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190816_2145'),
    ]

    operations = [
        migrations.RunPython(initDataToTables),
    ]
