# Generated by Django 2.1.7 on 2019-08-16 14:26

from django.db import migrations, models
import django.db.models.deletion

def initDataToUserTables(apps, schema_editor):
    User = apps.get_model("user", "User")
    Team = apps.get_model("user", "Team")
    team3 = Team.objects.get(id=3)
    user = User(user_id='admin', password='72230', championship='f2', privilege='ALL', is_admin=1, team=team3)
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190816_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team_id',
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Team'),
        ),
        migrations.RunPython(initDataToUserTables),
    ]
