# Generated by Django 2.1.7 on 2019-08-16 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190816_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('championship', models.CharField(choices=[('f2', 'f2'), ('f3', 'f3'), ('fe', 'fe')], default='f2', max_length=2)),
                ('start_time', models.DateTimeField(blank=True)),
                ('laps', models.IntegerField()),
                ('session_type', models.CharField(choices=[('PRACTICE', 'PRACTICE'), ('QUALIFYING', 'QUALIFYING'), ('RACE1', 'RACE1'), ('RACE2', 'RACE2')], max_length=12)),
                ('status', models.CharField(choices=[('ready', 'ready'), ('record', 'record'), ('finished', 'finished')], default='ready', max_length=10)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Circuit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
