# Generated by Django 3.0.7 on 2020-06-25 16:52

from django.db import migrations


def initDataToSessionTables(apps, schema_editor):
    Session = apps.get_model("user", "Session")
    User = apps.get_model("user", "User")
    Circuit = apps.get_model("user", "Circuit")
    Player = apps.get_model("user", "Player")
    Team = apps.get_model("user", "Team")
    # circuit
    circuit = Circuit(title='Autodromo Nazionale Monza', country='Italy', date='6 - 8 Sep', length='5.793', year='2019')
    circuit.save()
    circuit = Circuit(title='Sochi Autodrom', country='Russia', date='27 - 29 Sep', length='5.848', year='2019')
    circuit.save()
    circuit = Circuit(title='Spielberg', country='Austria', date='3 - 5 Jul', length='4.326', year='2020')
    circuit.save()
    # session
    user = User.objects.get(id=1)
    circuit = Circuit.objects.get(id=7)
    session = Session(title='F2. Autodromo Nazionale Monza - Sprint Race', championship='f2', start_time='2019-09-08 11:55:00', laps=21, session_type='RACE2', status='ready', circuit=circuit, user=user)
    session.save()
    user = User.objects.get(id=1)
    circuit = Circuit.objects.get(id=7)
    session = Session(title='F3. Autodromo Nazionale Monza - Sprint Race', championship='f3', start_time='2019-09-08 11:55:00', laps=22, session_type='RACE2', status='ready', circuit=circuit, user=user)
    session.save()
    user = User.objects.get(id=1)
    circuit = Circuit.objects.get(id=8)
    session = Session(title='F2. Sochi Autodrom - Sprint Race', championship='f2', start_time='2019-09-29 11:55:00', laps=21, session_type='RACE2', status='ready', circuit=circuit, user=user)
    session.save()
    user = User.objects.get(id=1)
    circuit = Circuit.objects.get(id=8)
    session = Session(title='F3. Sochi Autodrom - Sprint Race', championship='f3', start_time='2019-09-29 11:55:00', laps=20, session_type='RACE2', status='ready', circuit=circuit, user=user)
    session.save()
    user = User.objects.get(id=1)
    circuit = Circuit.objects.get(id=9)
    session = Session(title='F2. Spielberg - Feature Race', championship='f2', start_time='2020-07-05 11:55:00', laps=40, session_type='RACE1', status='ready', circuit=circuit, user=user)
    session.save()
    user = User.objects.get(id=1)
    circuit = Circuit.objects.get(id=9)
    session = Session(title='F2. Spielberg - Sprint Race', championship='f2', start_time='2020-07-05 11:55:00', laps=28, session_type='RACE2', status='ready', circuit=circuit, user=user)
    session.save()
    user = User.objects.get(id=1)
    circuit = Circuit.objects.get(id=9)
    session = Session(title='F3. Spielberg - Feature Race', championship='f3', start_time='2020-07-05 11:55:00', laps=24, session_type='RACE1', status='ready', circuit=circuit, user=user)
    session.save()
    user = User.objects.get(id=1)
    circuit = Circuit.objects.get(id=9)
    session = Session(title='F3. Spielberg - Sprint Race', championship='f3', start_time='2020-07-05 11:55:00', laps=24, session_type='RACE2', status='ready', circuit=circuit, user=user)
    session.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190816_2331'),
    ]

    operations = [
        migrations.RunPython(initDataToSessionTables),
    ]
