# Generated by Django 2.1.7 on 2019-08-16 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190816_2331'),
        ('formula_2_3', '0002_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RacingNumber', models.SmallIntegerField(null=True)),
                ('laps', models.SmallIntegerField(null=True)),
                ('positionValue', models.SmallIntegerField(null=True)),
                ('gap', models.CharField(max_length=50, null=True)),
                ('interval', models.CharField(max_length=50, null=True)),
                ('bestLap', models.SmallIntegerField(null=True)),
                ('bestValue', models.CharField(max_length=50, null=True)),
                ('sector1', models.CharField(max_length=50, null=True)),
                ('sector2', models.CharField(max_length=50, null=True)),
                ('sector3', models.CharField(max_length=50, null=True)),
                ('lastValue', models.CharField(max_length=50, null=True)),
                ('pits', models.SmallIntegerField(null=True)),
                ('statusRetired', models.SmallIntegerField(null=True)),
                ('statusInPit', models.SmallIntegerField(null=True)),
                ('statusPitOut', models.SmallIntegerField(null=True)),
                ('statusStopped', models.SmallIntegerField(null=True)),
                ('created_at', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Session')),
            ],
        ),
    ]
