# Generated by Django 2.1.7 on 2019-08-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190816_2331'),
        ('formula_2_3', '0003_auto_20190817_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(null=True)),
                ('RacingNumber', models.IntegerField(null=True)),
                ('PersonalBestLap', models.IntegerField(null=True)),
                ('PersonalBestLapPosition', models.IntegerField(null=True)),
                ('PersonalBestLapValue', models.CharField(max_length=50, null=True)),
                ('BestSectorsPosition0', models.IntegerField(null=True)),
                ('BestSectorsId0', models.IntegerField(null=True)),
                ('BestSectorsValue0', models.CharField(max_length=50, null=True)),
                ('BestSectorsPosition1', models.IntegerField(null=True)),
                ('BestSectorsId1', models.IntegerField(null=True)),
                ('BestSectorsValue1', models.CharField(max_length=50, null=True)),
                ('BestSectorsPosition2', models.IntegerField(null=True)),
                ('BestSectorsId2', models.IntegerField(null=True)),
                ('BestSectorsValue2', models.CharField(max_length=50, null=True)),
                ('BestSpeedsPosition0', models.IntegerField(null=True)),
                ('BestSpeedsId0', models.CharField(max_length=50, null=True)),
                ('BestSpeedsValue0', models.CharField(max_length=50, null=True)),
                ('BestSpeedsPosition1', models.IntegerField(null=True)),
                ('BestSpeedsId1', models.CharField(max_length=50, null=True)),
                ('BestSpeedsValue1', models.CharField(max_length=50, null=True)),
                ('BestSpeedsPosition2', models.IntegerField(null=True)),
                ('BestSpeedsId2', models.CharField(max_length=50, null=True)),
                ('BestSpeedsValue2', models.CharField(max_length=50, null=True)),
                ('BestSpeedsPosition3', models.IntegerField(null=True)),
                ('BestSpeedsId3', models.CharField(max_length=50, null=True)),
                ('BestSpeedsValue3', models.CharField(max_length=50, null=True)),
                ('created_at', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Session')),
            ],
        ),
    ]
