# Generated by Django 2.1.7 on 2019-08-16 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190816_2331'),
        ('formula_2_3', '0004_auto_20190817_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionTime', models.CharField(max_length=50, null=True)),
                ('sessionValue', models.TextField(null=True)),
                ('trackTime', models.CharField(max_length=50, null=True)),
                ('trackValue', models.TextField(null=True)),
                ('created_at', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Session')),
            ],
        ),
    ]
